name: Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 12.x
      TITLE: Home Lab

    steps:
      - uses: actions/checkout@v2
      - name: generate site
        uses: ./.github/actions/
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public